# Generated by Django 5.2.3 on 2025-06-30 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo del paciente", max_length=200
                    ),
                ),
                (
                    "apodo",
                    models.CharField(
                        blank=True, help_text="Apodo o alias", max_length=100, null=True
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "edad",
                    models.PositiveIntegerField(
                        blank=True, help_text="Edad en años", null=True
                    ),
                ),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "cedula",
                    models.CharField(
                        help_text="Cédula/Pasaporte/NUI", max_length=50, unique=True
                    ),
                ),
                (
                    "aseguradora",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nss",
                    models.CharField(
                        blank=True,
                        help_text="Número de Seguridad Social",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "grupo_sanguineo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("", "Desconocido"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kilogramos",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "talla_cm",
                    models.PositiveIntegerField(
                        blank=True, help_text="Talla en centímetros", null=True
                    ),
                ),
                (
                    "alergias",
                    models.TextField(
                        blank=True,
                        help_text="Descripción de alergias conocidas",
                        null=True,
                    ),
                ),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "nacionalidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
            },
        ),
        migrations.CreateModel(
            name="HistoriaClinicaEmergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora_llegada", models.DateTimeField()),
                (
                    "numero_expediente_clinico",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fecha_hora_clasificacion",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "prioridad_triaje",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Nivel I - Rojo (Resucitación)"),
                            ("II", "Nivel II - Naranja (Emergencia)"),
                            ("III", "Nivel III - Amarillo (Urgencia)"),
                            ("IV", "Nivel IV - Verde (Urgencia Menor)"),
                            ("V", "Nivel V - Azul (No Urgencia)"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "fecha_hora_fin_clasificacion",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "llego_medios_propios",
                    models.BooleanField(
                        default=False, verbose_name="Llegó por Medios Propios"
                    ),
                ),
                (
                    "llego_911",
                    models.BooleanField(default=False, verbose_name="Llegó por 9-1-1"),
                ),
                (
                    "llego_crue",
                    models.BooleanField(default=False, verbose_name="Llegó por CRUE"),
                ),
                (
                    "llego_ambulancia_privada",
                    models.BooleanField(
                        default=False, verbose_name="Llegó por Ambulancia Privada"
                    ),
                ),
                (
                    "paramedico_responsable",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "ambulancia_numero",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "acompanante_nombre",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "acompanante_parentesco",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "acompanante_telefono",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("acompanante_direccion", models.TextField(blank=True, null=True)),
                (
                    "motivo_cefalea",
                    models.BooleanField(default=False, verbose_name="Cefalea"),
                ),
                ("motivo_tos", models.BooleanField(default=False, verbose_name="Tos")),
                (
                    "motivo_palpitaciones",
                    models.BooleanField(default=False, verbose_name="Palpitaciones"),
                ),
                (
                    "motivo_hematemesis",
                    models.BooleanField(default=False, verbose_name="Hematemesis"),
                ),
                (
                    "motivo_disuria",
                    models.BooleanField(default=False, verbose_name="Disuria"),
                ),
                (
                    "motivo_melena",
                    models.BooleanField(default=False, verbose_name="Melena"),
                ),
                (
                    "motivo_mareos",
                    models.BooleanField(default=False, verbose_name="Mareos"),
                ),
                (
                    "motivo_epistaxis",
                    models.BooleanField(default=False, verbose_name="Epistaxis"),
                ),
                (
                    "motivo_nauseas",
                    models.BooleanField(default=False, verbose_name="Náuseas"),
                ),
                (
                    "motivo_dolor_toracico",
                    models.BooleanField(default=False, verbose_name="Dolor torácico"),
                ),
                (
                    "motivo_hematuria",
                    models.BooleanField(default=False, verbose_name="Hematuria"),
                ),
                (
                    "motivo_herida_arma",
                    models.BooleanField(
                        default=False,
                        verbose_name="Herida de arma blanca o arma de fuego",
                    ),
                ),
                (
                    "motivo_vomitos",
                    models.BooleanField(default=False, verbose_name="Vómitos"),
                ),
                (
                    "motivo_dolor_abdominal",
                    models.BooleanField(default=False, verbose_name="Dolor abdominal"),
                ),
                (
                    "motivo_sangrado_transvaginal",
                    models.BooleanField(
                        default=False, verbose_name="Sangrado transvaginal"
                    ),
                ),
                (
                    "motivo_intoxicacion",
                    models.BooleanField(default=False, verbose_name="Intoxicación"),
                ),
                (
                    "motivo_diarrea",
                    models.BooleanField(default=False, verbose_name="Diarrea"),
                ),
                (
                    "motivo_disnea",
                    models.BooleanField(default=False, verbose_name="Disnea"),
                ),
                (
                    "motivo_politraumatismo",
                    models.BooleanField(default=False, verbose_name="Politraumatismo"),
                ),
                (
                    "motivo_tec",
                    models.BooleanField(
                        default=False,
                        verbose_name="TEC (Traumatismo Encéfalo Craneano)",
                    ),
                ),
                (
                    "motivo_crisis_hipertensiva",
                    models.BooleanField(
                        default=False, verbose_name="Crisis hipertensiva"
                    ),
                ),
                (
                    "motivo_convulsiones",
                    models.BooleanField(default=False, verbose_name="Convulsiones"),
                ),
                (
                    "motivo_quemaduras",
                    models.BooleanField(default=False, verbose_name="Quemaduras"),
                ),
                (
                    "motivo_sincope",
                    models.BooleanField(default=False, verbose_name="Síncope"),
                ),
                (
                    "motivo_dolor_lumbar",
                    models.BooleanField(default=False, verbose_name="Dolor lumbar"),
                ),
                (
                    "motivo_otros_descripcion",
                    models.TextField(
                        blank=True, help_text="Especificar otros motivos", null=True
                    ),
                ),
                (
                    "motivo_consulta_principal_descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del motivo principal de la consulta",
                        null=True,
                    ),
                ),
                (
                    "enfermedad_actual_historia",
                    models.TextField(
                        blank=True,
                        help_text="Historia de la enfermedad actual y cronología",
                        null=True,
                    ),
                ),
                (
                    "antecedentes_personales_patologicos",
                    models.TextField(blank=True, null=True),
                ),
                ("antecedentes_quirurgicos", models.TextField(blank=True, null=True)),
                (
                    "antecedentes_ginecobstetricos",
                    models.TextField(blank=True, null=True),
                ),
                ("antecedentes_traumaticos", models.TextField(blank=True, null=True)),
                ("antecedentes_familiares", models.TextField(blank=True, null=True)),
                ("habitos_toxicos", models.TextField(blank=True, null=True)),
                ("medicamentos_uso_actual", models.TextField(blank=True, null=True)),
                (
                    "revision_sistemas_descripcion",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "presion_arterial_sistolica",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "presion_arterial_diastolica",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "frecuencia_cardiaca_lpm",
                    models.PositiveIntegerField(
                        blank=True, help_text="Latidos por minuto", null=True
                    ),
                ),
                (
                    "frecuencia_respiratoria_rpm",
                    models.PositiveIntegerField(
                        blank=True, help_text="Respiraciones por minuto", null=True
                    ),
                ),
                (
                    "temperatura_celsius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Grados Celsius",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "saturacion_oxigeno_porc",
                    models.PositiveIntegerField(
                        blank=True, help_text="Porcentaje SaO2", null=True
                    ),
                ),
                ("glasgow_ocular", models.PositiveIntegerField(blank=True, null=True)),
                ("glasgow_verbal", models.PositiveIntegerField(blank=True, null=True)),
                ("glasgow_motora", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "glasgow_total",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Suma de Glasgow (Ocular + Verbal + Motora)",
                        null=True,
                    ),
                ),
                (
                    "glucometria_mg_dl",
                    models.PositiveIntegerField(
                        blank=True, help_text="mg/dL", null=True
                    ),
                ),
                ("examen_fisico_descripcion", models.TextField(blank=True, null=True)),
                ("diagnostico_presuntivo", models.TextField(blank=True, null=True)),
                (
                    "diagnostico_definitivo_cie10",
                    models.CharField(
                        blank=True, help_text="Código CIE-10", max_length=20, null=True
                    ),
                ),
                (
                    "diagnostico_definitivo_descripcion",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "plan_tratamiento_indicaciones",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "destino_domicilio",
                    models.BooleanField(
                        default=False, verbose_name="Destino: Domicilio"
                    ),
                ),
                (
                    "destino_sala",
                    models.BooleanField(default=False, verbose_name="Destino: Sala"),
                ),
                (
                    "destino_uci",
                    models.BooleanField(default=False, verbose_name="Destino: UCI"),
                ),
                (
                    "destino_quirofano",
                    models.BooleanField(
                        default=False, verbose_name="Destino: Quirófano"
                    ),
                ),
                (
                    "destino_morgue",
                    models.BooleanField(default=False, verbose_name="Destino: Morgue"),
                ),
                (
                    "destino_transferencia",
                    models.BooleanField(
                        default=False,
                        verbose_name="Destino: Transferencia a otra unidad",
                    ),
                ),
                (
                    "destino_fuga",
                    models.BooleanField(default=False, verbose_name="Destino: Fuga"),
                ),
                (
                    "destino_otro",
                    models.BooleanField(
                        default=False, verbose_name="Destino: Otro (especificar)"
                    ),
                ),
                (
                    "destino_paciente_observaciones",
                    models.TextField(
                        blank=True,
                        help_text="Especificar destino 'Otro' o detalles adicionales",
                        null=True,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "medico_tratante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historias_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historias_emergencia",
                        to="gestion_historias.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia Clínica de Emergencia",
                "verbose_name_plural": "Historias Clínicas de Emergencia",
                "ordering": ["-fecha_hora_llegada"],
            },
        ),
    ]
